### ISSUE TITLE
Execute android test on github actions

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#24]
Running connected tests (Instrumented tests that runs on device or emulator) isn't well designed for CI.
With teamcity we need to handle and do it by hands.

As we are a public repository, we can try github actions that handle better that use case.
If it is applicable for tests, maybe migrate all teamcity builds to github actions.

- [x] Simple build
- [x] Running tests
- [x] Test with pr status check

**Comment by StaehliJ** [comment]
Running 4 simple instrumented test take at least 15min. Maybe executing such kind of test only when making a release ?

**Comment by defagos** [comment]
I configured [Pillarbox Apple](https://github.com/SRGSSR/pillarbox-apple) to run tests on PR only. This way checks are not performed during development on the issue branch, rather only when the PR is submitted (tests are also not run as long as the PR is kept in the draft state).
