### ISSUE TITLE
Pillarbox Web is available in a webview

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-android#373]
### Use case description

**As a Pillarbox web developer**, I'd like the web player to be available in a mobile webview, so I can easily test the web player in this context.

### Acceptance criteria

- Pillarbox web is available in a webview
- A DRM example is available
- The URL to embed in the WebView is https://srgssr.github.io/pillarbox-web/

**Resources**

- [WebChromeClient: onPermissionRequest](https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest))
- [Android search query](https://developer.android.com/s/results/?q=webview%20drm%20video)

**Comment by StaehliJ** [comment]
We try to implements like proposed here : https://amokranechentir.hashnode.dev/android-play-drm-protected-content-inside-a-webview

**Comment by StaehliJ** [comment]
The demo should be accessible inside PillarboxDemo android

**Comment by StaehliJ** [comment]
This demo migrate to https://github.com/SRGSSR/android-drm-pillarbox-web so we can close it.
