### ISSUE TITLE
Showcase NPAW integration with MediaItemTracker

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#427]
**As a user ** I wan to use NPAW adapter with Pillarbox.

NPAW library is available for Media3 so we can try to integrate it with Pillarbox.

https://bitbucket.org/npaw/media3-adapter-android/src/master/

# Acceptance criteria

- NPAW can be used with Pillarbox and work as expected.
- The integration is made with MediaItemTracker.

# Tasks

**Comment by defagos** [comment]
Won't do.
