### ISSUE TITLE
Analytics events aren't sent out if initialized too late

### ISSUE THREAD

**Issue by hoschiho** [SRGSSR/pillarbox-android#532]
### Description of the problem

We call `SRGAnalytics.init(application, config)` after we have consent from the user. However, in this case media player events aren't sent out. Manually triggered events like a page view event works correctly. And if we initialize it right in the main activity, everything works fine.

### Reproducibility

Always

### Steps to reproduce

Call `SRGAnalytics.init(application, config)` not right in the beginning. 

### Library version

1.0

### Operating system

Android 14

### Is there an existing issue for this?

- [X] I have searched existing issues and found no similar bug report.

**Comment by MGaetan89** [comment]
@hoschiho do you need more help on this issue? Or is the comment above what you were looking for?

**Comment by hoschiho** [comment]
@MGaetan89 All good :) Thanks for your help!
