### ISSUE TITLE
GetMaxDuration

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#558]
**As a integrator** I want to be able to customize the value of `Player.getMaxSeekToPreviousPosition` in order to change the time detection in `Player.seekToPrevious`.

# Acceptance criteria

- MaxSeekToPreviousPosition can be set when initializing Pillarbox player.

# Tasks

- [ ] Implement MediaController
- [ ] Implement ExoPlayer

**Comment by MGaetan89** [comment]
I have pushed my initial work to the [`558-getmaxduration`](https://github.com/SRGSSR/pillarbox-android/compare/558-getmaxduration?expand=1) branch.
I have also opened [an issue on `androidx/media`](https://github.com/androidx/media/issues/1425) to propose that it is integrated in Media3 directly. Based on the answer, the branch linked above may be dropped, and we can wait until a Media3 version that provides that feature.

**Comment by MGaetan89** [comment]
A PR has been opened on Media3 to support this feature: https://github.com/androidx/media/pull/1437

**Comment by MGaetan89** [comment]
The PR has been released in [AndroidX Media3 1.4.0-beta01](https://developer.android.com/jetpack/androidx/releases/media3#1.4.0-beta01).
