### ISSUE TITLE
Rename PlayerViewModel to PlayerState

### ISSUE THREAD

**Issue by fnberta** [SRGSSR/pillarbox-android#71]
### Use case description

This might be a bit nitpicking but I would suggest renaming `PlayerViewModel` to `PlayerState`. 

Let me try to explain why: The term view model has so many different meanings depending on what technical environment you're in. In Android, there is a specific framework component called `ViewModel` that has very specific behavior tied to retaining state for screens. I would argue that what is provided by `PlayerViewModel` is something else, it's exposing functions and properties to observe the video player state. Now, you could argue that this is in fact a view model and but given the Android environment we're in, it can lead to confusion. On top of that, there is actually a convention in compose world to call these things that represent UI state `...State`, e.g. `LazyListState`.

Given all that, I would suggest to rename to `PlayerState` to avoid any confusion and to align with commonly used patterns.

### Proposed solution

Rename `PlayerViewModel` to `PlayerState` and the corresponding function `rememberPlayerViewModel` to `rememberPlayerState`.

### Is there an existing similar feature request?

- [X] I have searched existing [features](https://github.com/SRGSSR/pillarbox-android/issues?q=is%3Aissue+label%3Aenhancement+) and found no similar request.

- [X] I have browsed the available API and found no way to achieve the use case I described.

**Comment by StaehliJ** [comment]
Good point, I was not 100% of the name at first too, as you mention it could be confusing with Android `ViewModel`.

As you can see the PlayerViewModel holds Flow to offer all the powerful mechanisms of Flow. The State part of Compose is done threw Composable extension.

I agree to rename `PlayerViewModel` to `PlayerState` it was my original thoughts.
