### ISSUE TITLE
Split BlockedTimeRange and Trackers data into seperated TrackGroup or Format

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#710]
**As a Pillarbox developer** I want to handle BlockedSegment and Trackers data into separate tracks.

Data can be split into

1. Track type for each kind of data.
2. Multiple TrackGroup of the same kind.
3. Multiple Format inside the same TrackGroup.

# Acceptance criteria

- Blocked time ranges and trackers data can be retrieve separatly. 

# Tasks

- [ ] ...

**Comment by MGaetan89** [comment]
Done as part of #717
